name: reusable workflow
on:
  workflow_dispatch:

jobs:
  call-workflow-ex4-reusable:
    uses: VianneyB0NTE/Formation-gh-actions-VB/.github/workflows/ex4_reusable.yaml@main
    with:
      node-version: 'lts/*'