name: cache
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v5
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
        - name: checkout
          uses: actions/checkout@v5
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            npm test
        - name: cache node modules
          id: cache-node-modules
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}